# my global config
global:
  scrape_interval: {{cfg.global.scrape_interval}}
  evaluation_interval: {{cfg.global.evaluation_interval}}
  scrape_timeout: {{cfg.global.scrape_timeout}}

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: '{{cfg.global.labels.default_label}}'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# Monitor Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

{{~#if cfg.scrape_configs}}
#
# Custom Scrape configurations start here
{{~#each cfg.scrape_configs}}
  - job_name: '{{job_name}}'
    {{~#if scrape_interval }}
    scrape_interval: {{scrape_interval}}
    {{~/if}}
    {{~#if scrape_timeout }}
    scrape_timeout: {{scrape_timeout}}
    {{~/if}}
    {{~#if metrics_path }}
    metrics_path: {{metrics_path}}
    {{~/if}}
    {{~#if target}}
    static_configs:
      - targets: ['{{target}}']
    {{~/if}}
{{/each}}
{{~/if}}
